language: node_js

# Run tests on 0.8 to match what we deploy on and 0.10 to match what most
# people are using in the wild.
node_js:
#   - "0.6"
  - "0.8"
  - "0.10"

# don't test production - the only real difference is that production has static
# assets committed. As these are generated as part of the test suite testing
# production would not tell us anything new.
branches:
  except:
    - production

services:
  - mongodb

before_install:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y update
  # don't try to install mongo as it conflicts with the mongo provided by travis
  # don't install compass using apt as the paths then get confused with the rnm. Use gem instead.
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|mongodb|compass)"`
  - gem install watir-webdriver pry compass


# The Watir tests will be set up to use FireFox which will then run headless using xvfb
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export WATIR_BROWSER=firefox

notifications:
  irc:
    channels:
      - "irc.mysociety.org#popit"
    use_notice: true

env:
  global:
    - LOGGLY_SUBDOMAIN=mysociety
    # the encrypted LOGGLY_INPUT_TOKEN entry
    - secure: "eR3a6RbnYMdNZcSeASapaYZSUO0gaUb8RVmOikHRQJUujsS0aGKIHPFwk22U\nmvhZlBeXwIX/jngK9A4kk8eRBDXybWG+JwZ1fWVH2GVe4pCEGQhONvsodXzF\njWOXXQyE7HFL/xyd+eE1r52hrDf+KvJCjRPmNJyMUATSZM9zSMA="
